export interface JobPortal {
  name: string;
  url: string;
  region: string;
  category: string;
}

export interface PortalCategory {
  id: string;
  label: string;
  description: string;
}

export const PORTAL_CATEGORIES: PortalCategory[] = [
  { id: 'global', label: '🌐 Global', description: 'Multi-region platforms' },
  { id: 'usa-canada', label: '🇺🇸 USA / 🇨🇦 Canada', description: 'North America' },
  { id: 'uk-ireland', label: '🇬🇧 UK & 🇮🇪 Ireland', description: 'United Kingdom & Ireland' },
  { id: 'europe', label: '🇪🇺 Europe', description: 'Continental Europe' },
  { id: 'india', label: '🇮🇳 India', description: 'India' },
  { id: 'sea', label: '🌏 Southeast Asia', description: 'Singapore, Malaysia, Indonesia, Philippines' },
  { id: 'asia', label: '🇯🇵 Japan / 🇰🇷 Korea / 🇨🇳 China / 🇹🇼 Taiwan', description: 'East Asia' },
  { id: 'oceania', label: '🇦🇺 Australia / 🇳🇿 New Zealand', description: 'Oceania' },
  { id: 'latam', label: '🌎 Latin America', description: 'Brazil, Mexico, Argentina, Chile, Spain' },
  { id: 'cis', label: '🇷🇺 Russia / 🇺🇦 CIS', description: 'Russia & CIS' },
  { id: 'me-africa', label: '🌍 Middle East & Africa', description: 'Gulf, North Africa, Sub-Saharan Africa' },
  { id: 'tech-remote', label: '💻 Tech & Remote', description: 'Tech, startup & remote specialists' },
  { id: 'gov-niche', label: '🏛️ Government & Niche', description: 'Public sector & special-interest' },
];

export const JOB_PORTALS: JobPortal[] = [
  // ── Global ──
  { name: 'Indeed', url: 'https://www.indeed.com', region: 'global', category: 'global' },
  { name: 'LinkedIn Jobs', url: 'https://www.linkedin.com/jobs', region: 'global', category: 'global' },
  { name: 'Glassdoor', url: 'https://www.glassdoor.com', region: 'global', category: 'global' },
  { name: 'Monster', url: 'https://www.monster.com', region: 'global', category: 'global' },
  { name: 'ZipRecruiter', url: 'https://www.ziprecruiter.com', region: 'global', category: 'global' },
  { name: 'CareerBuilder', url: 'https://www.careerbuilder.com', region: 'global', category: 'global' },
  { name: 'SimplyHired', url: 'https://www.simplyhired.com', region: 'global', category: 'global' },
  { name: 'CareerJet', url: 'https://www.careerjet.com', region: 'global', category: 'global' },
  { name: 'Adzuna', url: 'https://www.adzuna.com', region: 'global', category: 'global' },
  { name: 'Jooble', url: 'https://jooble.org', region: 'global', category: 'global' },
  { name: 'Jora', url: 'https://jora.com', region: 'global', category: 'global' },
  { name: 'Recruit.net', url: 'https://www.recruit.net', region: 'global', category: 'global' },
  { name: 'Talent.com', url: 'https://www.talent.com', region: 'global', category: 'global' },
  { name: 'Learn4Good', url: 'https://www.learn4good.com', region: 'global', category: 'global' },
  { name: 'JobisJob', url: 'https://www.jobisjob.com', region: 'global', category: 'global' },
  { name: 'Snagajob', url: 'https://www.snagajob.com', region: 'global', category: 'global' },
  { name: 'USAJobs (US Federal)', url: 'https://www.usajobs.gov', region: 'global', category: 'global' },
  { name: 'GovernmentJobs', url: 'https://www.governmentjobs.com', region: 'global', category: 'global' },
  { name: 'Working Nomads', url: 'https://www.workingnomads.com', region: 'global', category: 'global' },
  { name: 'Jobspresso', url: 'https://jobspresso.co', region: 'global', category: 'global' },
  { name: 'Himalayas', url: 'https://www.himalayas.app', region: 'global', category: 'global' },
  { name: 'Remotely.jobs', url: 'https://www.remotely.jobs', region: 'global', category: 'global' },
  { name: '4 Day Week', url: 'https://www.4dayweek.io', region: 'global', category: 'global' },
  { name: 'Pangian', url: 'https://www.pangian.com', region: 'global', category: 'global' },
  { name: 'Remote.co', url: 'https://remote.co', region: 'global', category: 'global' },
  { name: 'Remotive', url: 'https://remotive.com', region: 'global', category: 'global' },
  { name: 'RemoteOK', url: 'https://remoteok.com', region: 'global', category: 'global' },
  { name: 'WeWorkRemotely', url: 'https://weworkremotely.com', region: 'global', category: 'global' },
  { name: 'FlexJobs', url: 'https://www.flexjobs.com', region: 'global', category: 'global' },
  { name: 'Jobicy', url: 'https://jobicy.com', region: 'global', category: 'global' },
  { name: 'Levels.fyi Jobs', url: 'https://www.levels.fyi/jobs', region: 'global', category: 'global' },
  { name: 'Y Combinator Jobs', url: 'https://www.ycombinator.com/jobs', region: 'global', category: 'global' },
  { name: 'Wellfound (AngelList)', url: 'https://wellfound.com', region: 'global', category: 'global' },

  // ── USA / Canada ──
  { name: 'Dice (Tech)', url: 'https://www.dice.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Built In', url: 'https://www.builtin.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'VentureLoop', url: 'https://www.ventureloop.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Hired', url: 'https://www.hired.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Authentic Jobs', url: 'https://www.authenticjobs.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Workable', url: 'https://www.workable.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'eFinancialCareers', url: 'https://www.efinancialcareers.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'JobsBank Canada', url: 'https://www.jobbank.gc.ca', region: 'usa-canada', category: 'usa-canada' },
  { name: 'CareerBuilder Canada', url: 'https://www.careerbuilder.ca', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Indeed Canada', url: 'https://ca.indeed.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'Workopolis', url: 'https://www.workopolis.com', region: 'usa-canada', category: 'usa-canada' },
  { name: 'HigherEdJobs', url: 'https://www.higheredjobs.com', region: 'usa-canada', category: 'usa-canada' },

  // ── UK & Ireland ──
  { name: 'Reed', url: 'https://www.reed.co.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'TotalJobs', url: 'https://www.totaljobs.com', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'CV-Library', url: 'https://www.cv-library.co.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'Jobsite', url: 'https://www.jobsite.co.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'IT Jobs Watch', url: 'https://www.itjobswatch.co.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'NHS Jobs', url: 'https://www.jobs.nhs.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'Caterer (Hospitality)', url: 'https://www.caterer.com', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'Guardian Jobs', url: 'https://jobs.theguardian.com', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'Fish4Jobs', url: 'https://www.fish4.co.uk', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'WorkInIreland', url: 'https://www.workinireland.ie', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'Jobs.ie', url: 'https://www.jobs.ie', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'IrishJobs', url: 'https://www.irishjobs.ie', region: 'uk-ireland', category: 'uk-ireland' },
  { name: 'UK Civil Service Jobs', url: 'https://civilservicejobs.service.gov.uk', region: 'uk-ireland', category: 'uk-ireland' },

  // ── Europe ──
  { name: 'Arbeitsagentur (DE Gov)', url: 'https://www.arbeitsagentur.de', region: 'europe', category: 'europe' },
  { name: 'Monster Germany', url: 'https://www.monster.de', region: 'europe', category: 'europe' },
  { name: 'Jobs.ch (CH)', url: 'https://www.jobs.ch', region: 'europe', category: 'europe' },
  { name: 'SwissDevJobs (CH)', url: 'https://www.swissdevjobs.ch', region: 'europe', category: 'europe' },
  { name: 'Jobijoba (FR)', url: 'https://www.jobijoba.com', region: 'europe', category: 'europe' },
  { name: 'Pôle Emploi (FR Gov)', url: 'https://www.pole-emploi.fr', region: 'europe', category: 'europe' },
  { name: 'France Travail', url: 'https://www.france-travail.fr', region: 'europe', category: 'europe' },
  { name: 'Pracuj.pl', url: 'https://www.pracuj.pl', region: 'europe', category: 'europe' },
  { name: 'Jobs.cz (CZ)', url: 'https://www.jobs.cz', region: 'europe', category: 'europe' },
  { name: 'Profession.hu (HU)', url: 'https://www.profession.hu', region: 'europe', category: 'europe' },
  { name: 'MojPosao (HR)', url: 'https://www.mojposao.net', region: 'europe', category: 'europe' },
  { name: 'Jobindex.dk (DK)', url: 'https://www.jobindex.dk', region: 'europe', category: 'europe' },
  { name: 'Finn.no (NO)', url: 'https://www.finn.no', region: 'europe', category: 'europe' },
  { name: 'Monster Sweden', url: 'https://www.monster.se', region: 'europe', category: 'europe' },
  { name: 'Indeed Belgium', url: 'https://be.indeed.com', region: 'europe', category: 'europe' },
  { name: 'Jobat.be', url: 'https://www.jobat.be', region: 'europe', category: 'europe' },
  { name: 'Werk.nl (NL)', url: 'https://www.werk.nl', region: 'europe', category: 'europe' },
  { name: 'Monster Netherlands', url: 'https://www.monsterboard.nl', region: 'europe', category: 'europe' },
  { name: 'Arbeitnow (DE Tech)', url: 'https://arbeitnow.com', region: 'europe', category: 'europe' },
  { name: 'DevJobs Germany', url: 'https://devjobs.de', region: 'europe', category: 'europe' },
  { name: 'ITJobPro (DE)', url: 'https://www.itjobpro.com', region: 'europe', category: 'europe' },

  // ── India ──
  { name: 'Naukri', url: 'https://www.naukri.com', region: 'india', category: 'india' },
  { name: 'Shine.com', url: 'https://www.shine.com', region: 'india', category: 'india' },
  { name: 'Cutshort', url: 'https://www.cutshort.io', region: 'india', category: 'india' },
  { name: 'Instahyre', url: 'https://www.instahyre.com', region: 'india', category: 'india' },
  { name: 'Freshersworld', url: 'https://www.freshersworld.com', region: 'india', category: 'india' },
  { name: 'Apna', url: 'https://www.apna.co', region: 'india', category: 'india' },
  { name: 'Foundit (Monster India)', url: 'https://www.foundit.in', region: 'india', category: 'india' },
  { name: 'iimjobs', url: 'https://www.iimjobs.com', region: 'india', category: 'india' },
  { name: 'Hirist (Tech)', url: 'https://www.hirist.com', region: 'india', category: 'india' },
  { name: 'TimesJobs', url: 'https://www.timesjobs.com', region: 'india', category: 'india' },
  { name: 'LinkedIn India', url: 'https://in.linkedin.com/jobs', region: 'india', category: 'india' },

  // ── Southeast Asia ──
  { name: 'MyCareersFuture (SG Gov)', url: 'https://www.mycareersfuture.gov.sg', region: 'sea', category: 'sea' },
  { name: 'JobsCentral (SG)', url: 'https://www.jobscentral.com.sg', region: 'sea', category: 'sea' },
  { name: 'JobStreet (SG/MY)', url: 'https://www.jobstreet.com', region: 'sea', category: 'sea' },
  { name: 'JobsDB (SG/HK)', url: 'https://www.jobsdb.com', region: 'sea', category: 'sea' },
  { name: 'FastJobs (SG)', url: 'https://www.fastjobs.sg', region: 'sea', category: 'sea' },
  { name: 'Kalibrr (PH/ID)', url: 'https://www.kalibrr.com', region: 'sea', category: 'sea' },
  { name: 'JobStreet Philippines', url: 'https://www.jobstreet.com.ph', region: 'sea', category: 'sea' },
  { name: 'Tech in Asia Jobs', url: 'https://www.techinasia.com/jobs', region: 'sea', category: 'sea' },
  { name: 'Glints (SG/ID)', url: 'https://glints.com', region: 'sea', category: 'sea' },

  // ── East Asia ──
  { name: 'Daijob (JP)', url: 'https://www.daijob.com', region: 'asia', category: 'asia' },
  { name: 'Work in Japan', url: 'https://www.workinjapan.com', region: 'asia', category: 'asia' },
  { name: 'enJobs (JP)', url: 'https://www.enjobs.jp', region: 'asia', category: 'asia' },
  { name: 'Jobs in Japan', url: 'https://www.jobsinjapan.com', region: 'asia', category: 'asia' },
  { name: 'Japan Dev', url: 'https://japan-dev.com', region: 'asia', category: 'asia' },
  { name: 'Vorkers (JP)', url: 'https://www.vorkers.com', region: 'asia', category: 'asia' },
  { name: 'Indeed Japan', url: 'https://jp.indeed.com', region: 'asia', category: 'asia' },
  { name: 'Saramin (KR)', url: 'https://www.saramin.co.kr', region: 'asia', category: 'asia' },
  { name: 'JobKorea (KR)', url: 'https://www.jobkorea.co.kr', region: 'asia', category: 'asia' },
  { name: '51job (CN)', url: 'https://www.51job.com', region: 'asia', category: 'asia' },
  { name: 'Zhaopin (CN)', url: 'https://www.zhaopin.com', region: 'asia', category: 'asia' },
  { name: 'CakeResume (TW)', url: 'https://www.cakesresume.com', region: 'asia', category: 'asia' },

  // ── Oceania ──
  { name: 'Seek (AU)', url: 'https://www.seek.com.au', region: 'oceania', category: 'oceania' },
  { name: 'Jora Australia', url: 'https://au.jora.com', region: 'oceania', category: 'oceania' },
  { name: 'Indeed Australia', url: 'https://au.indeed.com', region: 'oceania', category: 'oceania' },
  { name: 'Trade Me Jobs (NZ)', url: 'https://www.trademe.co.nz/jobs', region: 'oceania', category: 'oceania' },
  { name: 'SEEK NZ', url: 'https://www.seek.co.nz', region: 'oceania', category: 'oceania' },

  // ── Latin America ──
  { name: 'Gupy (BR)', url: 'https://www.gupy.io', region: 'latam', category: 'latam' },
  { name: 'Vagas.com.br', url: 'https://www.vagas.com.br', region: 'latam', category: 'latam' },
  { name: 'Catho (BR)', url: 'https://www.catho.com.br', region: 'latam', category: 'latam' },
  { name: 'InfoJobs Brazil', url: 'https://www.infojobs.com.br', region: 'latam', category: 'latam' },
  { name: 'Computrabajo (LATAM)', url: 'https://www.computrabajo.com', region: 'latam', category: 'latam' },
  { name: 'Bumeran (AR/CL/PE)', url: 'https://www.bumeran.com', region: 'latam', category: 'latam' },
  { name: 'OCC Mundial (MX)', url: 'https://www.occ.com.mx', region: 'latam', category: 'latam' },
  { name: 'Empleos.net', url: 'https://www.empleos.net', region: 'latam', category: 'latam' },
  { name: 'GetOnBoard (LatAm Tech)', url: 'https://www.getonbrd.com', region: 'latam', category: 'latam' },
  { name: 'Laborum (CL)', url: 'https://www.laborum.cl', region: 'latam', category: 'latam' },
  { name: 'InfoJobs Spain', url: 'https://www.infojobs.net', region: 'latam', category: 'latam' },
  { name: 'Infoempleo (ES)', url: 'https://www.infoempleo.com', region: 'latam', category: 'latam' },
  { name: 'Tecnoempleo (ES)', url: 'https://www.tecnoempleo.com', region: 'latam', category: 'latam' },
  { name: 'Computrabajo Peru', url: 'https://pe.computrabajo.com', region: 'latam', category: 'latam' },
  { name: 'Computrabajo Colombia', url: 'https://co.computrabajo.com', region: 'latam', category: 'latam' },
  { name: 'Workana (LatAm Freelance)', url: 'https://www.workana.com', region: 'latam', category: 'latam' },

  // ── Russia / CIS ──
  { name: 'HeadHunter (RU)', url: 'https://hh.ru', region: 'cis', category: 'cis' },
  { name: 'SuperJob (RU)', url: 'https://www.superjob.ru', region: 'cis', category: 'cis' },
  { name: 'Rabota.ru', url: 'https://www.rabota.ru', region: 'cis', category: 'cis' },
  { name: 'Work.ua (UA)', url: 'https://www.work.ua', region: 'cis', category: 'cis' },
  { name: 'Robota.ua (UA)', url: 'https://www.robota.ua', region: 'cis', category: 'cis' },
  { name: 'Rabota.by (BY)', url: 'https://www.rabota.by', region: 'cis', category: 'cis' },

  // ── Middle East & Africa ──
  { name: 'Bayt.com', url: 'https://www.bayt.com', region: 'me-africa', category: 'me-africa' },
  { name: 'GulfTalent', url: 'https://www.gulftalent.com', region: 'me-africa', category: 'me-africa' },
  { name: 'NaukriGulf', url: 'https://www.naukrigulf.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Monster Gulf', url: 'https://www.monstergulf.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Wuzzuf (EG)', url: 'https://wuzzuf.net', region: 'me-africa', category: 'me-africa' },
  { name: 'MyJobMag (NG)', url: 'https://www.myjobmag.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Jobberman (NG/GH)', url: 'https://www.jobberman.com', region: 'me-africa', category: 'me-africa' },
  { name: 'BrighterMonday (KE)', url: 'https://www.brightermonday.co.ke', region: 'me-africa', category: 'me-africa' },
  { name: 'PulseJobs (NG)', url: 'https://www.pulsejobs.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Careers24 (ZA)', url: 'https://www.careers24.com', region: 'me-africa', category: 'me-africa' },
  { name: 'PNet (ZA)', url: 'https://www.pnet.co.za', region: 'me-africa', category: 'me-africa' },
  { name: 'CareerJunction (ZA)', url: 'https://www.careerjunction.co.za', region: 'me-africa', category: 'me-africa' },
  { name: 'Indeed South Africa', url: 'https://za.indeed.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Hot Nigerian Jobs', url: 'https://www.hotnigerianjobs.com', region: 'me-africa', category: 'me-africa' },
  { name: 'Jobzilla (NG)', url: 'https://www.jobzilla.ng', region: 'me-africa', category: 'me-africa' },
  { name: 'Jobberman Ghana', url: 'https://www.jobberman.com.gh', region: 'me-africa', category: 'me-africa' },
  { name: 'BrighterMonday UG', url: 'https://www.brightermonday.ug', region: 'me-africa', category: 'me-africa' },
  { name: 'JobCentre Kenya', url: 'https://www.jobcentre.co.ke', region: 'me-africa', category: 'me-africa' },
  { name: 'Recruiter.co.za', url: 'https://www.recruiter.co.za', region: 'me-africa', category: 'me-africa' },

  // ── Tech & Remote specialists ──
  { name: 'Wellfound (Startups)', url: 'https://wellfound.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'YC Work at a Startup', url: 'https://www.workatastartup.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Toptal', url: 'https://www.toptal.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Triplebyte', url: 'https://triplebyte.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Turing', url: 'https://www.turing.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Arc.dev', url: 'https://arc.dev', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Lemon.io', url: 'https://lemon.io', region: 'tech-remote', category: 'tech-remote' },
  { name: 'X-Team', url: 'https://x-team.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'NOALEO', url: 'https://www.noaleo.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Remoteintech', url: 'https://remoteintech.tech', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Developer Jobs', url: 'https://www.developerjobs.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'DataJobs.com', url: 'https://www.datajobs.com', region: 'tech-remote', category: 'tech-remote' },
  { name: 'Kandidate (Asia Tech)', url: 'https://www.kandidate.com', region: 'tech-remote', category: 'tech-remote' },

  // ── Government & Niche ──
  { name: 'USAJobs (US Federal)', url: 'https://www.usajobs.gov', region: 'gov-niche', category: 'gov-niche' },
  { name: 'UK Civil Service', url: 'https://civilservicejobs.service.gov.uk', region: 'gov-niche', category: 'gov-niche' },
  { name: 'NHS Jobs (UK Health)', url: 'https://www.jobs.nhs.uk', region: 'gov-niche', category: 'gov-niche' },
  { name: 'JobsBank (CA)', url: 'https://www.jobbank.gc.ca', region: 'gov-niche', category: 'gov-niche' },
  { name: 'MyCareersFuture (SG)', url: 'https://www.mycareersfuture.gov.sg', region: 'gov-niche', category: 'gov-niche' },
  { name: 'France Travail (FR)', url: 'https://www.france-travail.fr', region: 'gov-niche', category: 'gov-niche' },
  { name: 'TEFL.com', url: 'https://www.tefl.com', region: 'gov-niche', category: 'gov-niche' },
  { name: "Dave's ESL Cafe", url: 'https://www.daveseslcafe.com', region: 'gov-niche', category: 'gov-niche' },
  { name: 'GoAbroad', url: 'https://www.goabroad.com', region: 'gov-niche', category: 'gov-niche' },
  { name: 'Transitions Abroad', url: 'https://www.transitionsabroad.com', region: 'gov-niche', category: 'gov-niche' },
  { name: 'Expat.com', url: 'https://www.expat.com', region: 'gov-niche', category: 'gov-niche' },
  { name: 'EscapeArtist', url: 'https://www.escapeartist.com', region: 'gov-niche', category: 'gov-niche' },
];
